source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.0.0.rc1'
gem 'thin'
gem 'foreman'
gem 'pg'
gem 'protected_attributes'
gem 'active_model_serializers'
gem 'sass-rails', '~> 4.0.0.rc1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.0.1'
gem 'debugger', group: [:development, :test]
gem 'quiet_assets', group: [:development]
gem 'heroku'
gem 'rails_12factor'
gem 'jawbone-up', '~> 0.0.5'
gem 'faraday'
gem 'awesome_print'
gem 'withings-api'
